[features]
seeds = false
[programs.localnet]
learning = "CWrypf5PYX2m4abhtBpsynXCzz9QB5Bim9YBtB4TF1fJ"
puppet = "5cb1avvJp6Xev5vp3p7bLxGY91UsSLNFwjYAmdSrQzEY"
puppet_master = "3sXJMHkG2b4chuj7QpbC4Jdi74BCmFASBRY63rbz948p"
tic_tac_toe = "2QXMhVpni3MZ82bNNHp3Y7aBWZKk31M86RakY5mkASU5"
pda_eg = "77rG3XEQg63jeuasmVcxDxsnDUqRPKNX8AHRm1QjAC3F"
permissioned = "ADMMp4aPLZsrjbiv7NSMNrquDofnnm6Dh3ra6dRoB5nA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "learningKeypair.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
learning = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/learning/learning.ts"
puppet_master = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/puppet_master/puppet_master.ts"
tic_tac_toe = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tic_tac_toe/tic_tac_toe.ts"
pda_eg = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pda_eg/pda_eg.ts"
wallet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/api/wallet_address.ts"
token_mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/api/token_mint_address.ts"
permissioned = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/permissioned/permissioned.ts"