[features]
seeds = false
[programs.localnet]
learning = "AgSmLGJvPPhtg5g5C1bXBbwpJqDRW6SwXKKKBJjtqP9Z"
puppet = "EpMS9dNS8UQffqtuYtnTgFd1GA7VpzCAfc44mktBxEzX"
puppet_master = "7heuPnsQxZmQgEs96PcduTH5utWyXhiQkXRZtHWyTeD2"
tic_tac_toe = "2QXMhVpni3MZ82bNNHp3Y7aBWZKk31M86RakY5mkASU5"
pda_eg = "77rG3XEQg63jeuasmVcxDxsnDUqRPKNX8AHRm1QjAC3F"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "learningKeypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
learning = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/learning/learning.ts"
puppet_master = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/puppet_master/puppet_master.ts"
tic_tac_toe = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tic_tac_toe/tic_tac_toe.ts"
pda_eg = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pda_eg/pda_eg.ts"
wallet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/api/wallet_address.ts"
token_mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/api/token_mint_address.ts"